version: '3'

volumes:
  rainloop-root:
  rainloop-data:

services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - rainloop-root:/rainloop
    depends_on:
      - application
    ports:
      - 1337:80
    networks:
      - default
      - nginxproxy

  application:
    image: hermsi/alpine-rainloop
    volumes:
      - rainloop-root:/rainloop
      - rainloop-data:/rainloop/data
    networks:
      default:
        aliases:
          - rainloop